theme: jekyll-theme-cayman
title: Fundamentals of Computer Science
author: Stephen Zq
description: Introduction to the science of computers, algorithms, computer organization, flowchart design, computing systems, programming concepts, data structures, nonnumerical applications, introductory numerical methods For Computer Science, Computer Engineering, Mathematics, and Science majors but open to all qualified students.
